POST http://localhost:8080/login
content-type: application/json

{
    "username": "user",
    "password": "user"
}

###
GET http://localhost:8080/protected
content-type: application/json

{
    
}

###
POST http://localhost:2000/getaToken
content-type: application/json

{
     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWEzNWZjZGZkMzNlZDU0OTk3YjUyNzEiLCJpYXQiOjE2MzkxNDYzMTh9.cxyEyrf73rMCsbuJDOaa4yZatpZC3bM-G4YpJEiv0UE"
}

###
DELETE http://localhost:2000/logout
content-type: application/json

{
    "refreshToken":
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWEzNWZjZGZkMzNlZDU0OTk3YjUyNzEiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjM5MTY1MTU4fQ.9XJSd1qQjSa1WkpxbL_Ht44JTc9zrurmKLFFdYEQWmM"
}
###
GET http://localhost:8080/b
content-type: application/json

{
}