const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const flightSchema = new Schema({
  flightNumber: { type: String, unique: true },
  arrivalTime: { type: Date },
  departureTime: { type: Date },
  // Date does include time as well
  // arrivalDate: {type:Date},
  // departureDate: {type:Date},
  economySeatsNum: { type: Number },
  businessSeatsNum: { type: Number },
  firstSeatsNum: { type: Number },
  departureAirport: { type: String },
  arrivalAirport: { type: String },
  firstClassPrice: { type: Number },
  arrivalTerminal: { type: String },
  departureTerminal: { type: Number },
  economyClassPrice: { type: Number },
  businessClassPrice: { type: Number },
  arrivalTerminal: { type: String },
  departureTerminal: { type: String },

  avaiableSeats: {
    type: [String],
    default: [
      "1A",
      "1B",
      "1C",
      "1D",
      "1E",
      "1F",
      "2A",
      "2B",
      "2C",
      "2D",
      "2E",
      "2F",
      "3A",
      "3B",
      "3C",
      "3D",
      "3E",
      "3F",
      "4A",
      "4B",
      "4C",
      "4D",
      "4E",
      "4F",
      "5A",
      "5B",
      "5C",
      "5D",
      "5E",
      "5F",
      "6A",
      "6B",
      "6C",
      "6D",
      "6E",
      "6F",
      "7A",
      "7B",
      "7C",
      "7D",
      "7E",
      "7F",
      "8A",
      "8B",
      "8C",
      "8D",
      "8E",
      "8F",
      "9A",
      "9B",
      "9C",
      "9D",
      "9E",
      "9F",
      "10A",
      "10B",
      "10C",
      "10D",
      "10E",
      "10F",
    ],
  },
});
module.exports = mongoose.model("Flight", flightSchema);
